package api

import (
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/google/rficonductorv2/backend/internal/services"
)

type ExportHandler struct {
	rfiArchitect *services.RfiArchitectAgent
	demoAgent    *services.DemoScriptAgent
	execAgent    *services.ExecutiveReviewAgent
	timeline     *services.TimelineEngine
}

func NewExportHandler(
	rfiArchitect *services.RfiArchitectAgent,
	demoAgent *services.DemoScriptAgent,
	execAgent *services.ExecutiveReviewAgent,
	timeline *services.TimelineEngine,
) *ExportHandler {
	return &ExportHandler{
		rfiArchitect: rfiArchitect,
		demoAgent:    demoAgent,
		execAgent:    execAgent,
		timeline:     timeline,
	}
}

func (h *ExportHandler) ExportDeepDiveReport(c *gin.Context) {
	report := c.DefaultQuery("report", "devsecops")
	isCNAP := strings.Contains(strings.ToLower(report), "cnap")
	nowStr := time.Now().UTC().Format("January 02, 2026 (15:04 UTC)")

	filename := "universal_analyst_evaluation_deep_dive_report.md"
	if isCNAP {
		filename = "gartner_cnap_mq_strategic_evaluation_deep_dive_report.md"
	}

	content := fmt.Sprintf(`# Universal Analyst Evaluation & RFI Orchestration Report
## Deep Dive Analysis: Portfolio Eligibility, Rejection Deficits, & Dual-Input Workback Schedule
**Generated By:** Analyst Response Agent (ARA)  
**Execution Timestamp:** %s  
**Applicable Evaluation Frameworks:** Gartner Magic Quadrants (MQs) & Critical Capabilities, Forrester Waves, and IDC MarketScapes  

---

## 1. Executive Summary & Universal Analyst Scope

Industry analyst evaluations across **Gartner, Forrester, and IDC** increasingly evaluate AI Coding Agents and GenAI developer platforms under rigorous, dual-axis methodologies: combining **market presence/financial viability thresholds** with **deep technical architecture and demonstration validations**.

### Extracted Universal Inclusion Boundaries
* **General Availability (GA) & Market Participation:** Offerings must be generally available (GA), fully supported for enterprise production, and purchasable via public price sheets by the analyst cutoff date.
* **Financial & Enterprise Scale Floors (Option A vs. Option B):**
  * **Option A (Logo Floor):** >= 500 paying enterprise customer organizations.
  * **Option B (Revenue & Growth Floor):** >= $25M recognized GAAP annualized revenue AND >= 40%% YoY revenue growth (CAGR).
* **Multi-Product Demonstration Rules:** Dedicated demonstration tracks and portal uploads for each product SKU.

---

## 2. Comprehensive Welcome Packet & RFI Alignment Matrices
* **Qualifying Core SKUs:** Gemini Code Assist Enterprise ($35M Rev / 620 Logos), Cloud Build ($95M Rev / 2,800 Logos), Cloud Deploy ($42M Rev / 850 Logos), Artifact Registry ($110M Rev / 3,200 Logos), SCC Enterprise ($180M Rev / 1,900 Logos), Antigravity 2.0 ($145M Rev / 2,100 Logos).
* **Rejected Offerings with Remediation:**
  * **Gemini Code Assist Agent Mode (Preview):** GA Cutoff Deficit (April 15 scheduled GA vs March 02 cutoff). Remediation: Submit Deficit Attestation Waiver and position in Stage 2 Roadmap Demonstration module.
  * **Cloud Legacy Code Helper (Deprecated):** Scale Deficits ($12M Rev / 15%% CAGR / 210 Logos). Remediation: Exclude from evaluation.
`, nowStr)

	c.Header("Content-Disposition", fmt.Sprintf(`attachment; filename="%s"`, filename))
	c.Header("Cache-Control", "no-cache")
	c.Data(http.StatusOK, "text/markdown; charset=utf-8", []byte(content))
}

func (h *ExportHandler) ExportWorkbackSchedule(c *gin.Context) {
	format := strings.ToLower(c.DefaultQuery("format", "md"))
	targetDeadline := time.Date(2026, 6, 20, 17, 0, 0, 0, time.UTC)
	timeline := h.timeline.GenerateTimeline(targetDeadline, nil)

	if format == "csv" {
		lines := []string{"7-Phase Operational Process,Milestone Name,Offset (Days),Target Date,Shifted Status,Shift Reason"}
		for _, ms := range timeline.Milestones {
			dtStr := ms.TargetDate.Format("2006-01-02 15:04 UTC")
			shiftStatus := "On Schedule"
			if ms.Shifted {
				shiftStatus = "Shifted"
			}
			lines = append(lines, fmt.Sprintf(`"%s","%s",%d,%s,%s,"%s"`,
				ms.OperationalPhase, ms.Name, ms.OffsetDays, dtStr, shiftStatus, ms.ShiftReason))
		}
		csvContent := strings.Join(lines, "\n") + "\n"
		c.Header("Content-Disposition", `attachment; filename="universal_workback_schedule.csv"`)
		c.Header("Cache-Control", "no-cache")
		c.Data(http.StatusOK, "text/csv; charset=utf-8", []byte(csvContent))
		return
	}

	lines := []string{
		"# Universal Analyst Evaluation — Exclusive Workback Schedule",
		fmt.Sprintf("**Generated:** %s  ", time.Now().UTC().Format("2006-01-02 15:04 UTC")),
		fmt.Sprintf("**External Deadline:** %s  ", targetDeadline.Format("2006-01-02 15:04 UTC")),
		"**Active Exclusion Windows:** Cloud Next 2026 Conference Freeze (June 14–16, 2026)  ",
		"",
		"| 7-Phase Operational Process | Milestone / Activity | Offset | Target Date | Status & Blackout Shifts |",
		"| :--- | :--- | :---: | :---: | :--- |",
	}
	for _, ms := range timeline.Milestones {
		dtStr := ms.TargetDate.Format("2006-01-02")
		statusStr := "✅ On Schedule"
		if ms.Shifted {
			statusStr = fmt.Sprintf("⚠️ %s", ms.ShiftReason)
		}
		lines = append(lines, fmt.Sprintf("| **%s** | **%s** | `T-%d Days` | `%s` | %s |",
			ms.OperationalPhase, ms.Name, ms.OffsetDays, dtStr, statusStr))
	}
	lines = append(lines, "")
	mdContent := strings.Join(lines, "\n")

	c.Header("Content-Disposition", `attachment; filename="universal_workback_schedule.md"`)
	c.Header("Cache-Control", "no-cache")
	c.Data(http.StatusOK, "text/markdown; charset=utf-8", []byte(mdContent))
}

func (h *ExportHandler) ExportKickoffDeck(c *gin.Context) {
	report := c.DefaultQuery("report", "devsecops")
	isCNAP := strings.Contains(strings.ToLower(report), "cnap")
	nowStr := time.Now().UTC().Format("January 02, 2026")

	var deckContent string
	var filename string

	if isCNAP {
		filename = "2026_cnap_mq_kickoff_presentation_deck.md"
		deckContent = fmt.Sprintf(`# 2026 Gartner Magic Quadrant™ for Cloud-Native Application Platforms (CNAP)
## Executive Stakeholder Kickoff Presentation Deck
**Generated By:** Conductor v3 (Go Distroless Engine)  
**Date:** %s  
**Classification:** Confidential — Internal Strategic Guidance  

---

## Slide 1: Title & Operational Overview
* **Report Focus:** 2026 Gartner Magic Quadrant™ for Cloud-Native Application Platforms (CNAP)
* **Primary Objectives:** Solidify Google Cloud leadership placement and advance ahead on the "Ability to Execute" axis.
* **Key Deliverables:** 121-Question RFI Spreadsheet & 45-Minute Maximum Video Demonstration across 5 core modules.

## Slide 2: 2025 YoY Performance & Strategy
* **2026 Strategic Goal:** Showcase sub-50ms serverless scale-from-zero execution on Cloud Run and GKE Enterprise multi-cluster governance.
`, nowStr)
	} else {
		filename = "universal_kickoff_presentation_deck.md"
		deckContent = fmt.Sprintf(`# 2026 Gartner Magic Quadrant™ for DevSecOps & Universal Code Platforms
## Executive Stakeholder Kickoff Presentation Deck
**Generated By:** Conductor v3 (Go Distroless Engine)  
**Date:** %s  
**Classification:** Confidential — Internal Strategic Guidance  

---

## Slide 1: Executive Kickoff & Governance Charter
* **Report Scope:** Universal Code & Agent Platforms / DevSecOps Platforms, 2026.
* **Target Milestone:** Strict adherence to corporate exclusion windows and demonstration freezes.

## Slide 2: Stage 2 Video Recording Budget Guidelines (60m Cap)
* **Module Budget:** Strict 10-15 minute budget per assigned SME domain lead.
* **Video Quality:** Minimum 720p resolution, high-contrast UI, and verified TOC bookmark chapters.
`, nowStr)
	}

	c.Header("Content-Disposition", fmt.Sprintf(`attachment; filename="%s"`, filename))
	c.Header("Cache-Control", "no-cache")
	c.Data(http.StatusOK, "text/markdown; charset=utf-8", []byte(deckContent))
}

func (h *ExportHandler) ExportRfiResponses(c *gin.Context) {
	format := strings.ToLower(c.DefaultQuery("format", "md"))
	report := c.DefaultQuery("report", "devsecops")
	isCNAP := strings.Contains(strings.ToLower(report), "cnap")

	rfiData, err := h.rfiArchitect.GenerateGroundedDrafts(c.Request.Context(), report)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"detail": err.Error()})
		return
	}

	filePrefix := "gartner_rfi_completed_responses"
	if isCNAP {
		filePrefix = "gartner_cnap_rfi_completed_responses"
	}

	if format == "csv" {
		lines := []string{
			`"Worksheet Tab Domain","Section Coordinate","Question & Capability Requirement","Assigned SME Lead","Offered Natively","Prior RFI Source Title","Historical Question Match","Grounding Confidence Score","Pre-Populated Technical Draft Response"`,
		}
		for _, q := range rfiData.Questions {
			lines = append(lines, fmt.Sprintf(`"%s","%s","%s","%s","Yes (Native)","%s","%s","%.1f%%","%s"`,
				q.WorksheetTab, q.SectionID, q.QuestionText, q.AssignedSME, q.SourceRfiTitle, q.SourceQuestionText, q.GroundingConfidenceScore, q.DraftResponse))
		}
		csvContent := strings.Join(lines, "\n") + "\n"
		c.Header("Content-Disposition", fmt.Sprintf(`attachment; filename="%s.csv"`, filePrefix))
		c.Header("Cache-Control", "no-cache")
		c.Data(http.StatusOK, "text/csv; charset=utf-8", []byte(csvContent))
		return
	}

	nowStr := time.Now().UTC().Format("2006-01-02 15:04 UTC")
	lines := []string{
		"# 2026 Gartner Magic Quadrant & Critical Capabilities — Completed RFI Technical Responses",
		"**Generated By:** Principal TSA Sub-Agent Grounded RAG Ingestion  ",
		fmt.Sprintf("**Timestamp:** %s  ", nowStr),
		fmt.Sprintf("**Report Scope:** %s  ", rfiData.ReportName),
		fmt.Sprintf("**Average Grounding Confidence:** %.1f%% (Validated against verified GA Catalog)  ", rfiData.AverageGroundingConfidence),
		"",
		"## Summary Capability Evaluation Matrix",
		"",
		"| Worksheet Tab & Section | Requirement Question | Assigned SME | Offered Natively | Proven RAG Source & Grounding Score |",
		"| :--- | :--- | :---: | :--- | :---: |",
	}

	for _, q := range rfiData.Questions {
		lines = append(lines, fmt.Sprintf("| **%s** | %s | `%s` | **Yes (Native)** | *%s* (`%.1f%%`) |",
			q.SectionID, q.QuestionText, q.AssignedSME, q.SourceRfiTitle, q.GroundingConfidenceScore))
	}

	lines = append(lines, "", "---", "", "## Detailed Pre-Populated RAG Narratives by Worksheet Tab", "")
	for _, q := range rfiData.Questions {
		lines = append(lines,
			fmt.Sprintf("### %s — %s", q.SectionID, q.QuestionText),
			fmt.Sprintf("* **Assigned Domain Lead:** `%s`", q.AssignedSME),
			fmt.Sprintf("* **Grounding Confidence Score:** `%.1f%%`", q.GroundingConfidenceScore),
			fmt.Sprintf("* **Prior RFI Source Citation & Provenance:** `%s`", q.SourceRfiTitle),
			fmt.Sprintf("* **Grounded Technical Draft Response:**  \n  > %s (Backed by Google Cloud Support SLAs)", q.DraftResponse),
			"",
			"---",
			"",
		)
	}

	mdContent := strings.Join(lines, "\n")
	c.Header("Content-Disposition", fmt.Sprintf(`attachment; filename="%s.md"`, filePrefix))
	c.Header("Cache-Control", "no-cache")
	c.Data(http.StatusOK, "text/markdown; charset=utf-8", []byte(mdContent))
}

func (h *ExportHandler) ExportDemoPlaybook(c *gin.Context) {
	report := c.DefaultQuery("report", "devsecops")
	content := h.demoAgent.GeneratePlaybookMarkdown(report)
	isCNAP := strings.Contains(strings.ToLower(report), "cnap")
	filename := "gartner_demo_script_playbook.md"
	if isCNAP {
		filename = "gartner_cnap_demo_script_playbook.md"
	}

	c.Header("Content-Disposition", fmt.Sprintf(`attachment; filename="%s"`, filename))
	c.Header("Cache-Control", "no-cache")
	c.Data(http.StatusOK, "text/markdown; charset=utf-8", []byte(content))
}

func (h *ExportHandler) ExportExecutiveReviewMemo(c *gin.Context) {
	report := c.DefaultQuery("report", "devsecops")
	content := h.execAgent.GenerateReviewMemoMarkdown(report)
	isCNAP := strings.Contains(strings.ToLower(report), "cnap")
	filename := "gartner_executive_review_memo.md"
	if isCNAP {
		filename = "gartner_cnap_executive_review_memo.md"
	}

	c.Header("Content-Disposition", fmt.Sprintf(`attachment; filename="%s"`, filename))
	c.Header("Cache-Control", "no-cache")
	c.Data(http.StatusOK, "text/markdown; charset=utf-8", []byte(content))
}

func (h *ExportHandler) ExportFinalPublicationBundle(c *gin.Context) {
	report := c.DefaultQuery("report", "devsecops")
	isCNAP := strings.Contains(strings.ToLower(report), "cnap")
	scopeStr := "Universal Code & Agent Platforms / DevSecOps Platforms, 2026"
	filename := "gartner_final_publication_and_recognition.md"
	if isCNAP {
		scopeStr = "Cloud-Native Application Platforms (CNAP), 2026"
		filename = "gartner_cnap_final_publication_and_recognition.md"
	}
	nowStr := time.Now().UTC().Format("2006-01-02 15:04 UTC")

	content := fmt.Sprintf(`# 🏆 Phase 7: Master Portal Publication Package & Contributor Recognition Manifesto
**Report Scope:** %s  
**Timestamp:** %s  
**Overall Operational Lifecycle Status:** 100%% COMPLETE & APPROVED FOR UPLOAD  

## 1. Master Portal Submission Readiness Checklist
All evaluation materials have been validated:
* **Section 1: RFI Workbook:** Pre-Populated Technical RFI Questionnaire (.CSV & .MD) -> READY FOR PORTAL UPLOAD
* **Section 2: TOC Bookmarks:** Timecoded Table of Contents Bookmarks -> READY FOR PORTAL UPLOAD
* **Section 3: Demo Media:** Master Screencast Demonstration Recordings (720p+ .MP4) -> READY FOR PORTAL UPLOAD
* **Section 4: Waiver Dossier:** Executive Approval & Deficit Attestation Memo -> READY FOR PORTAL UPLOAD

---

## 2. 🌟 Executive Contributor Recognition Manifesto
We proudly recognize and commend all contributing domain champions across enterprise leadership channels.
`, scopeStr, nowStr)

	c.Header("Content-Disposition", fmt.Sprintf(`attachment; filename="%s"`, filename))
	c.Header("Cache-Control", "no-cache")
	c.Data(http.StatusOK, "text/markdown; charset=utf-8", []byte(content))
}
