package services

import (
	"fmt"
	"strings"
	"time"
)

type DemoScriptAgent struct{}

func NewDemoScriptAgent() *DemoScriptAgent {
	return &DemoScriptAgent{}
}

func (s *DemoScriptAgent) GeneratePlaybookMarkdown(reportName string) string {
	isCNAP := strings.Contains(strings.ToLower(reportName), "cnap")
	nowStr := time.Now().UTC().Format("January 02, 2026")

	if isCNAP {
		return "# 2026 Gartner Magic Quadrant™ for Cloud-Native Application Platforms (CNAP)\n" +
			"## Master On-Demand Demonstration Script Playbook & Timecoded Storyboard\n" +
			"**Generated By:** Analyst Response Agent (ARA) Demo Script Engine  \n" +
			fmt.Sprintf("**Execution Date:** %s  \n", nowStr) +
			"**Mandatory Timing Boundary:** **45 Minutes Overall Cap** across 5 demonstrated modules  \n" +
			"**Video Specifications:** 720p+ resolution, 60fps screencast in .mp4 format (< 4GB)\n\n" +
			"---\n\n" +
			"## 1. Executive Summary & Timecode Index (Table of Contents)\n\n" +
			"Evaluators will cease scoring at exactly 45:00. Each module lead must adhere to strict time boundaries.\n\n" +
			"| Timecode Bookmark | Module Name | Primary Presenter | Target Duration | Satisfied Critical Capabilities |\n" +
			"| :--- | :--- | :--- | :---: | :--- |\n" +
			"| **[00:00 - 08:30]** | **Module 1: Serverless Container Scaling & Cold Starts** | `serverless-sme@google.com` | 08m 30s | Cloud Run Concurrency, Scale-to-Zero & Cold Start Mitigation |\n" +
			"| **[08:30 - 18:00]** | **Module 2: GKE Enterprise & Fleet Orchestration** | `gke-sme@google.com` | 09m 30s | Multi-cluster Mesh, Autopilot & Workload Identity |\n" +
			"| **[18:00 - 27:00]** | **Module 3: Application Design Center (ADC) Blueprints** | `idp-sme@google.com` | 09m 00s | Golden Paths, Infrastructure-as-Code & Topology Governance |\n" +
			"| **[27:00 - 36:30]** | **Module 4: Enterprise DevSecOps & SLSA Provenance** | `sec-sme@google.com` | 09m 30s | Binary Authorization, Artifact Registry & Vulnerability Scanning |\n" +
			"| **[36:30 - 45:00]** | **Module 5: Day-2 Observability & Automated Remediation** | `ops-sme@google.com` | 08m 30s | Cloud Trace, AutoCloud Incident Response & SPACE Framework |\n\n" +
			"---\n\n" +
			"## 2. Module 1 Step-by-Step Script: Serverless Runtime (00:00 - 08:30)\n" +
			"* **Visual Action:** Open Google Cloud Console -> Cloud Run -> Deploy service with min-instances=0.\n" +
			"* **Verbatim Voiceover:** \"Welcome to the Google Cloud CNAP demonstration. We begin by showcasing Cloud Run's sub-50ms cold start latency with statically compiled distroless containers...\"\n"
	}

	return "# 2026 Gartner Magic Quadrant™ for DevSecOps & Universal Code Platforms\n" +
		"## Master On-Demand Demonstration Script Playbook & Timecoded Storyboard\n" +
		"**Generated By:** Analyst Response Agent (ARA) Demo Script Engine  \n" +
		fmt.Sprintf("**Execution Date:** %s  \n", nowStr) +
		"**Mandatory Timing Boundary:** **60 Minutes Overall Cap** across all demonstrated use cases  \n" +
		"**Video Specifications:** 720p+ resolution in .mp4 format (< 4GB)\n\n" +
		"---\n\n" +
		"## 1. Executive Summary & Timecode Index (Table of Contents)\n\n" +
		"Evaluators will cease scoring at exactly 60:00.\n\n" +
		"| Timecode Bookmark | Module Name | Primary Presenter | Target Duration | Satisfied Critical Capabilities |\n" +
		"| :--- | :--- | :--- | :---: | :--- |\n" +
		"| **[00:00 - 14:30]** | **Module 1: Agentic Code Transformation & IDE Flow** | `devsecops-sme@google.com` | 14m 30s | Gemini Code Assist Enterprise & Antigravity IDE |\n" +
		"| **[14:30 - 29:00]** | **Module 2: Automated CI/CD & Progressive Delivery** | `cicd-sme@google.com` | 14m 30s | Cloud Build, Cloud Deploy & SLSA Level 3 Provenance |\n" +
		"| **[29:00 - 44:00]** | **Module 3: Software Supply Chain Security & SBOM** | `security-sme@google.com` | 15m 00s | Artifact Registry & Security Command Center |\n" +
		"| **[44:00 - 59:30]** | **Module 4: DORA & SPACE Productivity Telemetry** | `ops-sme@google.com` | 15m 30s | Developer Connect Insights & Autonomous Cloud |\n\n" +
		"---\n\n" +
		"## 2. Module 1 Script: Agentic Code Transformation (00:00 - 14:30)\n" +
		"* **Visual Action:** Launch Antigravity IDE -> Prompt multi-file refactoring -> Accept inline diff.\n" +
		"* **Verbatim Voiceover:** \"Notice how Gemini Code Assist Enterprise indexes the entire repository context locally to generate verified unit tests...\"\n"
}
